### ISSUE TITLE
Changes outside of terraform result in an erroring terraform plan

### ISSUE THREAD

**Issue by michvllni** [coder/terraform-provider-coderd#100]
I deleted a template outside of terraform because it was broken and I had issues with adding an additional parameter to it.

When I ran a terraform plan afterwards to restore the template, it failed with the following error:
╷
│ Error: Client Error
│ 
│   with coderd_template.templates["kubernetes"],
│   on templates.tf line 2, in resource "coderd_template" "templates":
│    2: resource "coderd_template" "templates" {
│ 
│ Failed to get template: GET
│ https://REDACTED/api/v2/templates/REDACTED:
│ unexpected status code 404: Resource not found or you do not have access to
│ this resource
╵

I would have expected the provider to detect changes outside of terraform and be able to handle them

**Comment by ethanndickson** [comment]
I think it's reasonable for resources to mark themselves as deleted if fetching them fails with a 404 status code. Hashicorp would appear to [agree](https://developer.hashicorp.com/terraform/plugin/framework/resources/read) - will fix!.

**Comment by ethanndickson** [comment]
Thanks for reporting all these issues! The fixes are all available in the latest release (today!) :)
