### ISSUE TITLE
Support setting max port sharing level in template resource 

### ISSUE THREAD

**Issue by stirby** [coder/terraform-provider-coderd#108]
We should allow users to configure the maximum port sharing level in the template resource, as we do in the settings UI. 

https://coder.com/docs/networking/port-forwarding#configure-maximum-port-sharing-level-enterprise

**Comment by stirby** [comment]
cc @ethanndickson

**Comment by ethanndickson** [comment]
The setting was previously missing from the `Create` request, which I added here: https://github.com/coder/coder/pull/14366. If customers are actually looking to set this via the provider, I can add it in a backwards compatible way by sending a `PATCH` with it if the attribute is configured.

**Comment by ethanndickson** [comment]
Closed by #110.
