### ISSUE TITLE
new resource coderd_template_version

### ISSUE THREAD

**Issue by michvllni** [coder/terraform-provider-coderd#122]
For integration purposes, I think it would be a good addition to be able to create the versions for a template as a separate resource:

```hcl
resource "coderd_template" "example" {
  name = "example-template"  
  allow_user_cancel_workspace_jobs = false
}

resource "coderd_template_version" "example" {
  template_id = coderd_template.example.id
  directory     = "./example-template"
  active        = true
  tf_vars = [{
    name  = "image_id"
    value = "ami-12345678"
  }]
}
```

In my use case I create several templates simoultanously via for_each and I'm having a hard time to determine which version to update. By doing something as suggested it would be way simpler (for example via count)

**Comment by ethanndickson** [comment]
This was actually the original design, but it would have required fairly significant Coder API changes, as you can't currently create a template without a version.

**Comment by michvllni** [comment]
Fair point
