### ISSUE TITLE
Add support for organization resources, provisioners and org, group, role sync

### ISSUE THREAD

**Issue by ethanndickson** [coder/terraform-provider-coderd#39]
This allows users to create and manage multi-org Coder deployments using Terraform.
Although the organization API hasn't been finalised/released, we can implement an initial version of this.
The resource should allow users to create and assign custom organization-wide roles.

- org operations
- provisioner keys
- group/role sync

*nice-to-have*
- org sync

**Comment by bpmct** [comment]
Also group, org, role sync

**Comment by ethanndickson** [comment]
Worth mentioning that tests for this should use the new `statecheck` package - it feels a lot more ergonomic, though I'm not totally convinced it's worth porting the existing tests over.

Example: https://github.com/hashicorp/terraform-provider-random/pull/599

**Comment by bpmct** [comment]
@aslilac is this completed by #131?

**Comment by aslilac** [comment]
that's just one piece of the puzzle. I've got at least one more PR to merge to make a certain customer happy, and there are a couple more pieces after that even.
