### ISSUE TITLE
add `--private` to `coderd_template` resource

### ISSUE THREAD

**Issue by matifali** [coder/terraform-provider-coderd#73]
We should also add `private` to the coderd terraform provider. 
<https://codercom.slack.com/archives/C014JH42DBJ/p1723784869912859|https://codercom.slack.com/archives/C014JH42DBJ/p1723784869912859>

[Slack Message](https://codercom.slack.com/archives/C05TWBJ02TU/p1723785524384059?thread_ts=1723785524.384059&cid=C05TWBJ02TU)

**Comment by bpmct** [comment]
Chatted with Ethan about this, `--private` is an abstraction for the ACLs (e.g. who it is shared with) so you can accomplish the same thing via the permissions in the provider.

**Comment by matifali** [comment]
For folks who visit this issue in future,
Setting `groups = []` in `acl` should achieve the same.
