### ISSUE TITLE
Change on tf_vars should also trigger a new template version

### ISSUE THREAD

**Issue by michvllni** [coder/terraform-provider-coderd#97]
Currently, a change in the tf_vars property does not trigger a recreation but a modification of the template.

As the tf_vars effectively change the content of the template, it should trigger a new version.

As an example, it would be possible to change the name of a parameter via tf_var.

A more drastic example to show what would be possible is to base the entire coder parameters on a tf_var:

template.tf
```hcl
resource "coderd_template" "example" {
  name        = "example"
  description = "example"

  versions = [
    {
      directory = "./template"
      active    = true
      tf_vars = [{
        name = "parameters"
        value = jsonencode([
          "cpu",
          "memory"
        ])
      }]
    }
  ]
}

```

in the template:
```hcl
variable "parameters" {
  type = string
}

locals {
  parameters = jsondecode(var.parameters)
}

data "coder_parameter" "parameters" {
  for_each = toset(local.parameters)
  name     = each.key
}
```

If I change the content of the parameters var via the coderd_template in this scenario, the whole template would change.

**Comment by michvllni** [comment]
Just saw that the vars in coder are defined on the template level, not the project level. What happens if I push two versions with different vars via coderd... which values for the vars will be promoted in the template?

Or is this only on a UI?

**Comment by ethanndickson** [comment]
> Just saw that the vars in coder are defined on the template level, not the project level. What happens if I push two versions with different vars via coderd... which values for the vars will be promoted in the template?

I was also confused by this, but the Terraform variables shown on template settings are populated from the active template version. However, they are applied template-wide.  If you created a new version using `coder templates push` and didn't supply them as CLI args, they'd be populated in that new version using the existing variables.

Regardless, we very much have a bug in the provider, as it needs to be pushing a new template version when `tf_vars` changes. This is what the Web UI does when saving changes to `Template Settings -> Variables`.

**Comment by michvllni** [comment]
Okay, thank you for the confirmation.

Out of curiosity: if I switch the active template version to an older one, will the vars get overwritten by the vars of the old template?
